### ISSUE TITLE
Isolate tenant's database

### ISSUE THREAD

**Issue by jahnavisana2812** [supabase/supavisor#290]
# Improve documentation

## Link 
https://supabase.github.io/supavisor/configuration/tenants/
## Describe the problem

I'm currently operating Supavisor on a locally hosted PostgreSQL server, enabling me to create tenants within a specific database. Given that there's a product serving multiple clients from this single database, the objective is to configure each tenant in accordance with its respective client. Is it possible to isolate each tenant's data?If yes can you please share any documentation on how this can be executed ?

**Comment by fenos** [comment]
@jahnavisana2812 Your use case seems more aligned with the use of RLS policies.

Potentially Supavisor could be injecting the tenant-id as a local configuration during connection, ex: `SELECT set_config('supavisor.tenant_id', 'abcd')` so that you can apply RLS policies using this value.

currently is not setting this option afaik, but you could use this same approach at the application level.

```
const client = sqlClient.connection()

// session mode
client.raw(`SELECT set_config('pooler.tenant_id', request.tenantId', false)` 

// tnx mode
const tnx = await client.transaction()
tnx.raw(`SELECT set_config('pooler.tenant_id', request.tenantId', true)` 

tnx.select('*').from('sometable')
```

then with the proper RLS it will isolate data for each tenant
